version: "3.8"
services:
  odoo-demo:
    restart: unless-stopped
    ports:
      - "8069:8069"

  postgres-demo:
    ports:
      - "5434:5432"
    restart: unless-stopped

  # nginx-demo:
  #   restart: always
  #   ports:
  #     - "81:80"